spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:grad_stepup}
    username: ${DB_USERNAME:bj_grad}
    password: ${DB_PASSWORD:}



  flyway:
    locations: classpath:db/migration
    enabled: true