spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/${DB_NAME:grad_stepup}
    username: ${DB_USERNAME:bj_grad}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect



  flyway:
    locations: classpath:db/migration
    enabled: true